name: plume
description: "A gentle yet powerful rich text editor."
version: 0.0.1
publish_to: None

workspace:
  - document_model

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  generate: true

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  document_model:

  parchment_delta: ^1.0.0
  collection: ^1.19.1
  intl: ">=0.19.0 <0.21.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.26.2
  flutter_lints: ^6.0.0
  fake_async: ^1.3.3
  mocktail: ^1.0.4
