name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.1"
          cache: true
          # Manually Update this `key`
          cache-key: "3.35.1"
      - run: dart pub global activate coverage

      - name: Plume - Install dependencies
        run: flutter pub get

      - name: Plume - Verify formatting
        run: dart format . --output=none --set-exit-if-changed

      - name: Plume - Analyze project source
        run: flutter analyze --fatal-infos

      - name: Plume - Run tests
        run: flutter test --coverage

      - name: Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage/lcov.info,./packages/parchment/coverage/lcov.info
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
